version: '3.4'

services:
  backend:
    container_name: 'node-server'
    build: './server/'
    environment:
      JWT_SECRET: 'engvnangvneroakngoin'
    ports:
      - '5000:5000'
  db:
    image: 'postgres:12'
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data
